### ISSUE TITLE
Provide paper feedback

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#58]
The paper is really shaping up!

Provide detailed text comments on explore, analyze and data this cycle (skipping case studies for now).

**Comment by wrgr** [comment]
Success here means generating 4 issues and assigning as appropriate:
- [x] Store - messaged @kunallillaney  https://github.com/neurodata/ndpaper/issues/57
- [x] Explore - @alexbaden & i discussed getting histograms working per ROI. he will make a new issue about that on monday.
- [x] Analyze - messaged @willgray and updated https://github.com/neurodata/ndpaper/issues/59 
- [x] Figures - @MrAE was busy with SIMPLEX responsibliities this week, and spends on 1 day a week doing non-research, he and i will connect and make an issue first thing next week.
- [x] Data - https://github.com/neurodata/ndpaper/issues/61 is the outcome of my conversations with @alexbaden about tables and figures

**Comment by jovo** [comment]
can success be defined by commenting on 4 open issues?

**Comment by wrgr** [comment]
i'm down with that, but ideally should be explicit, external, and detailed review (e.g., not "make figure better", but a review of existing content)

**Comment by jovo** [comment]
so, a list of revisions for each person's 1 issue?
people still have 2 issues, so it will be a bit complicated, but i'll try...

On Mon, Jun 13, 2016 at 2:37 PM, William Gray notifications@github.com
wrote:

> i'm down with that, but ideally should be explicit, external, and detailed
> review (e.g., not "make figure better", but a review of existing content)
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/58#issuecomment-225568727,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcjpilc96754wcS6w4tAN47D0zbUIks5qLU77gaJpZM4Iy2rH
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
these will be ready for you by tomorrow.  not due for almost a week.  pardon our dust while i restructure.

**Comment by jovo** [comment]
all good.

On Mon, Jun 13, 2016 at 10:28 PM, William Gray notifications@github.com
wrote:

> these will be ready for you by tomorrow. not due for almost a week. pardon
> our dust while i restructure.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/58#issuecomment-225698212,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcsw6YiGv1R3jIJO5bDPGk4Cf_epvks5qLb1WgaJpZM4Iy2rH
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
